import { useState } from 'react';
import { RelayProjectBrainOrb } from './RelayProjectBrainOrb';
import type { ProjectBrainState } from './contracts';
import type { RelayBrainDocument } from '../../shared/llmops';

/**
 * THE PROJECT BRAIN'S OWN VIEW.
 *
 * Opened from the Brain object in the workspace, and it keeps that object as
 * its centrepiece rather than replacing it with a chart — the thing the
 * founder clicked should still be there when they arrive.
 *
 * WHAT IT SHOWS IS WHAT RELAY ACTUALLY HAS. The sections are
 * `RelayBrainDocument.sections`, generated by the Brain itself; this component
 * invents none of them and adds no headings of its own. When no generator has
 * run there is no document, and that is said in those words — a project with
 * nothing recorded and a deployment that generates nothing are different
 * facts, and neither of them is an empty chart.
 *
 * PROGRESSIVE DISCLOSURE. One section is open at a time. The direction is
 * explicit that this must not become a dashboard dumping every field on one
 * screen, and the honest reason is the same: a wall of text is how a surface
 * stops being read.
 */

export interface RelayProjectBrainViewProps {
  state: ProjectBrainState;
  /**
   * What the current Mission RETRIEVED, as references.
   *
   * References, never content — the Brain records that something was observed
   * and never absorbs what it claimed, and rendering retrieved text here would
   * put untrusted content inside the surface built to display honesty.
   *
   * Absent means the Mission was authorised to read nothing. An empty array
   * means it was authorised and retrieved none, and the two are shown
   * differently because they are different facts.
   */
  evidence?: readonly {
    readonly evidenceId: string;
    readonly source: string;
    readonly reference: string;
    readonly publishedAt: string | null;
    readonly retrievedAt: string;
    readonly actualBackendId: string | null;
    readonly fallbackOccurred: boolean;
  }[];
  document?: RelayBrainDocument;
  reducedMotion?: boolean;
  /** Return to the workspace the Brain was opened from. */
  onClose: () => void;
}

export function RelayProjectBrainView({
  state,
  evidence,
  document: brainDocument,
  reducedMotion = false,
  onClose,
}: RelayProjectBrainViewProps) {
  const sections = brainDocument?.sections ?? [];
  const [open, setOpen] = useState<string | null>(sections[0]?.heading ?? null);

  return (
    <section className="rpb-view" aria-labelledby="rpb-view-heading">
      <header className="rpb-view-header">
        <h1 id="rpb-view-heading" className="rpb-view-title">PROJECT BRAIN</h1>
        <button type="button" className="rpb-view-close" onClick={onClose}>
          ← BACK TO PROJECT
        </button>
      </header>

      <div className="rpb-view-stage">
        <RelayProjectBrainOrb
          size={220}
          reducedMotion={reducedMotion}
          populated={state.entries > 0}
        />
      </div>

      {/* The three counts the Brain has always reported, kept as facts rather
          than promoted into headline metrics. `lastUpdate` stays a dash when
          absent: unknown is not a date. */}
      <dl className="rpb-view-counts">
        <div>
          <dt>APPROVED ENTRIES</dt>
          <dd>{state.entries}</dd>
        </div>
        <div>
          <dt>LAST UPDATE</dt>
          <dd>{state.lastUpdate ?? '—'}</dd>
        </div>
        <div>
          <dt>PENDING APPROVALS</dt>
          <dd className={state.pendingApprovals > 0 ? 'rpw-brain-pending' : undefined}>
            {state.pendingApprovals}
          </dd>
        </div>
      </dl>

      {/* WHAT THIS MISSION READ. Above the document, because it is the newest
          thing the Brain knows and the thing a founder checking freshness came
          for. Absent and empty are rendered differently. */}
      {evidence !== undefined && (
        <section className="rpb-view-evidence" aria-label="Retrieved evidence">
          <h2 className="rpb-view-evidence-heading">RETRIEVED FOR THIS MISSION</h2>
          {evidence.length === 0 ? (
            <p className="rpb-view-empty">
              This Mission was authorised to read something and retrieved nothing.
            </p>
          ) : (
            <ul className="rpb-view-evidence-list">
              {evidence.map((item) => (
                <li key={item.evidenceId}>
                  <a href={item.reference} rel="noreferrer noopener" target="_blank">
                    {item.reference}
                  </a>
                  <span className="rpb-view-evidence-meta">
                    {`${item.source} · published ${item.publishedAt ?? 'UNKNOWN'} · retrieved ${item.retrievedAt}`}
                    {` · via ${item.actualBackendId ?? 'UNKNOWN'}`}
                    {item.fallbackOccurred ? ' (fallback)' : ''}
                  </span>
                </li>
              ))}
            </ul>
          )}
        </section>
      )}

      {brainDocument === undefined ? (
        <p className="rpb-view-empty">
          No Brain document has been generated for this project. Relay shows what it has
          recorded, and it has recorded nothing here yet.
        </p>
      ) : (
        <>
          <p className={brainDocument.stale ? 'rpw-brain-stale' : 'rpw-brain-fresh'}>
            {brainDocument.stale ? 'STALE — ' : 'CURRENT — '}
            {brainDocument.freshness}
          </p>

          {/* WHAT THE BRAIN IS ACTUALLY HOLDING.
              The document already separates durable knowledge from what it is
              holding provisionally, what it DROPPED, and what is waiting on
              approval — and the workspace panel reported none of it. An
              eviction count is a fact about the Brain's limits; omitting it
              makes a bounded memory look unbounded. */}
          <dl className="rpb-view-memory">
            <div>
              <dt>DURABLE KNOWLEDGE</dt>
              <dd>{brainDocument.longTermEntries}</dd>
            </div>
            <div>
              <dt>SELF-APPROVED</dt>
              <dd>{brainDocument.selfApprovedEntries}</dd>
            </div>
            <div>
              <dt>HOLDING NOW</dt>
              <dd>{brainDocument.shortTermEntries}</dd>
            </div>
            <div>
              <dt>DROPPED</dt>
              <dd>{brainDocument.shortTermEvicted}</dd>
            </div>
            <div>
              <dt>AWAITING APPROVAL</dt>
              <dd>{brainDocument.pendingProposals}</dd>
            </div>
            <div>
              <dt>NEWEST INPUT</dt>
              {/* Null stays null. A Brain that has received nothing is not a
                  Brain that received something at the epoch. */}
              <dd>{brainDocument.newestInputAt ?? 'Unknown'}</dd>
            </div>
          </dl>
          <div className="rpb-view-sections">
            {sections.map((section) => {
              const isOpen = open === section.heading;
              return (
                <section key={section.heading} className="rpb-view-section">
                  <h2>
                    <button
                      type="button"
                      className="rpb-view-section-toggle"
                      aria-expanded={isOpen}
                      onClick={() => setOpen(isOpen ? null : section.heading)}
                    >
                      <span aria-hidden="true">{isOpen ? '▾' : '▸'}</span>{' '}
                      {section.heading}
                      <span className="rpb-view-section-count">{section.lines.length}</span>
                    </button>
                  </h2>
                  {isOpen && (
                    <ul className="rpw-brain-doc-lines">
                      {section.lines.map((line) => <li key={line}>{line}</li>)}
                    </ul>
                  )}
                </section>
              );
            })}
          </div>
        </>
      )}
    </section>
  );
}
