import type { RelayDemoEvent, RelayDemoRole, RelayDemoStep } from './demo-simulation-types';

export const DEMO_SCENARIO_ID = 'normalize-project-name';
export const DEMO_ALLOWED_FILE = 'src/normalize.js';
export const DEMO_TEST_COMMAND = 'npm test';

function event(
  sequence: number,
  role: RelayDemoRole,
  category: string,
  title: string,
  summary: string,
  visualState: string,
  extra: Partial<Pick<RelayDemoEvent, 'relatedFile' | 'command' | 'result'>> = {},
): RelayDemoEvent {
  return {
    id: `demo-event-${sequence}`,
    sequence,
    category,
    role,
    title,
    summary,
    truthClass: 'simulated_demo',
    simulatedAtMs: sequence * 1000,
    visualState,
    ...extra,
  };
}

export const RELAY_DEMO_SCRIPT: readonly RelayDemoStep[] = [
  {
    id: 'ready',
    label: 'READY',
    activeRole: 'founder',
    durationMs: 1600,
    headline: 'Founder request received',
    summary: 'Implement normalizeProjectName with a bounded, test-verified change.',
    details: ['Trim input', 'Convert to lowercase', 'Normalize words to hyphen-separated text'],
    event: event(1, 'founder', 'request', 'Demo mission initialized', 'Founder request staged locally for the offline demonstration.', 'READY'),
  },
  {
    id: 'contract',
    label: 'MISSION CONTRACT CREATED',
    activeRole: 'founder',
    durationMs: 1800,
    headline: 'Mission boundaries locked',
    summary: 'One allowed file, protected paths, required test, no network, independent review required.',
    details: [DEMO_ALLOWED_FILE, 'Protected: package-lock.json · relay-bridge/ · production mission state', DEMO_TEST_COMMAND],
    event: event(2, 'founder', 'contract', 'Mission contract created', 'Scope, evidence, network, and review requirements recorded.', 'MISSION CONTRACT'),
  },
  {
    id: 'architect',
    label: 'ANALYZING MISSION',
    activeRole: 'prompt_architect',
    durationMs: 3400,
    headline: 'ChatGPT · Prompt Architect',
    summary: 'Interpreting the request and preparing explicit acceptance criteria.',
    details: ['Constraints extracted', 'Acceptance criteria created', 'Implementation task prepared'],
    event: event(3, 'prompt_architect', 'architect', 'Prompt Architect assigned', 'Requirements converted into an implementation-ready mission package.', 'ANALYZING'),
  },
  {
    id: 'alcatraz',
    label: 'PREPARING HANDOFF',
    activeRole: 'alcatraz',
    durationMs: 3400,
    headline: 'Sunday Alcatraz · Intelligence coordination',
    summary: 'Checking mission alignment and preserving constraints before delegation.',
    details: ['Implementation route selected', 'Project Brain updated', 'Structured handoff validated'],
    event: event(4, 'alcatraz', 'coordination', 'Project Brain updated', 'Mission alignment checked and approved context prepared.', 'PREPARING HANDOFF'),
  },
  {
    id: 'handoff',
    label: 'HANDOFF READY',
    activeRole: 'alcatraz',
    durationMs: 2400,
    headline: 'Structured handoff validated',
    summary: 'Objective, file boundary, protected paths, required test, and completion evidence are pinned.',
    details: ['Responsibility: implement normalization only', `Allowed: ${DEMO_ALLOWED_FILE}`, `Required proof: ${DEMO_TEST_COMMAND}`],
    event: event(5, 'alcatraz', 'handoff', 'Prompt Architect handoff prepared', 'Context passed without expanding scope.', 'HANDOFF READY'),
  },
  {
    id: 'implement',
    label: 'IMPLEMENTING',
    activeRole: 'coding_agent',
    durationMs: 5600,
    headline: 'Claude Code · Coding Agent',
    summary: 'Preparing a deterministic simulated patch inside the assigned file.',
    details: ['SIMULATED assignment received', 'SIMULATED file inspected', 'SIMULATED patch prepared', 'SIMULATED claim submitted'],
    event: event(6, 'coding_agent', 'implementation', 'Simulated implementation captured', 'Assigned file updated in the visual demonstration only.', 'IMPLEMENTING', { relatedFile: DEMO_ALLOWED_FILE, result: 'CLAIM SUBMITTED · UNVERIFIED' }),
  },
  {
    id: 'verify',
    label: 'VERIFYING',
    activeRole: 'relay_verifier',
    durationMs: 3400,
    headline: 'Relay deterministic verification',
    summary: 'Checking scope, protected paths, required test, and artifact revision.',
    details: ['Changed-file scope checked', 'Protected files unchanged', 'Required test evaluated', 'Artifact revision demo-r1 captured'],
    event: event(7, 'relay_verifier', 'verification', 'Initial verification passed', 'Simulated evidence bound to artifact demo-r1.', 'VERIFYING', { command: DEMO_TEST_COMMAND, result: 'SIMULATED PASS' }),
  },
  {
    id: 'review',
    label: 'REVIEWING',
    activeRole: 'reviewer',
    durationMs: 4400,
    headline: 'Hermes · Reviewer · Read only',
    summary: 'Reviewing artifact demo-r1 independently from the simulated coding role.',
    details: ['Current artifact inspected', 'Requirements cross-checked', 'Blocking defect identified'],
    event: event(8, 'reviewer', 'review', 'Finding F-1 recorded', 'Repeated existing hyphens are not collapsed.', 'REVIEWING', { result: 'CHANGES REQUIRED' }),
  },
  {
    id: 'revision',
    label: 'REVISION REQUIRED',
    activeRole: 'reviewer',
    durationMs: 4600,
    headline: 'Finding F-1 · Blocking',
    summary: 'Repeated hyphens are not collapsed, so the normalization contract is not yet satisfied.',
    details: ['Affected requirement: canonical hyphen separation', 'Repair owner: Claude Code', 'Attempt limit: 1 bounded repair'],
    event: event(9, 'reviewer', 'finding', 'Revision required', 'Relay recorded F-1 and created scope-locked repair R-1.', 'REVISION REQUIRED', { relatedFile: DEMO_ALLOWED_FILE }),
  },
  {
    id: 'repair',
    label: 'REPAIRING',
    activeRole: 'repair',
    durationMs: 4200,
    headline: 'Claude Code · Bounded repair',
    summary: 'Collapsing repeated hyphens without expanding the assigned scope.',
    details: ['Original simulated context preserved', 'Only the allowed file revised', 'Artifact advanced to demo-r2'],
    event: event(10, 'repair', 'repair', 'Repair R-1 captured', 'Repeated-hyphen normalization added in the simulated artifact.', 'REPAIRING', { relatedFile: DEMO_ALLOWED_FILE }),
  },
  {
    id: 'reverify',
    label: 'VERIFYING REPAIR',
    activeRole: 'relay_verifier',
    durationMs: 3400,
    headline: 'Relay re-verification',
    summary: 'Verifying the repaired artifact and invalidating review evidence bound to demo-r1.',
    details: ['Repair scope checked', 'Protected paths unchanged', 'Relevant tests passed', 'Previous review marked STALE'],
    event: event(11, 'relay_verifier', 'reverification', 'Re-verification passed', 'Evidence rebound to artifact demo-r2; prior review is stale.', 'VERIFYING REPAIR', { command: DEMO_TEST_COMMAND, result: 'SIMULATED PASS · demo-r2' }),
  },
  {
    id: 'final-review',
    label: 'REVIEWING REPAIR',
    activeRole: 'reviewer',
    durationMs: 4400,
    headline: 'Hermes · Final review · Read only',
    summary: 'Reviewing current artifact demo-r2 and the resolution evidence for F-1.',
    details: ['Finding F-1 resolved', 'All requirements checked', 'No blocking finding remains', 'Approval bound to demo-r2'],
    event: event(12, 'reviewer', 'final_review', 'Final reviewer approval recorded', 'Hermes approved current simulated artifact demo-r2.', 'REVIEWING REPAIR', { result: 'SIMULATED APPROVAL · demo-r2' }),
  },
  {
    id: 'complete',
    label: 'DEMO VERIFIED COMPLETE',
    activeRole: 'complete',
    durationMs: 0,
    headline: 'Demo mission contract satisfied',
    summary: 'Scope preserved, evidence present, finding repaired, and current artifact independently approved.',
    details: ['Required evidence present', 'Independent review complete', 'F-1 resolved by R-1', 'Final artifact demo-r2 approved'],
    event: event(13, 'complete', 'completion', 'Demo completion decision recorded', 'Simulation complete. No production completion authority was used.', 'DEMO VERIFIED COMPLETE', { result: 'SIMULATION COMPLETE' }),
  },
] as const;
